language: php

php:
  - 5.5.9
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
   - php: hhvm
  fast_finish: true

install:
  - wget https://github.com/satooshi/php-coveralls/releases/download/v0.7.0/coveralls.phar
  - composer self-update
  - composer install

script:
 - vendor/bin/phpunit -v

after_success:
 - travis_retry php coveralls.phar -v
